Importing correct library
The use of "mmpeg" library was throwing `"AttributeError: module 'ffmpeg' has no attribute 'input'"`

That was due to the incorrect "ffmpeg" library being installed. It seems the intended library is in fact [ffmpeg-python](https://github.com/kkroening/ffmpeg-python).
More info in this issue: https://github.com/kkroening/ffmpeg-python/issues/174